<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Vehicle extends Model
{
    use HasFactory;

    protected $fillable = [
        'make',
        'model',
        'year',
        'price',
        'stock_number',
        'badge',
        'rego_num',
        'vin',
        'engine_number',
        'serial_number',
        'special_price',
        'odometer',
        'body',
        'color',
        'interior_colour',
        'engine_size',
        'engine_make',
        'cylinders',
        'gear_type',
        'gear_count',
        'fuel_type',
        'drive',
        'door_num',
        'wheel_size',
        'wheels',
        'axle_configuration',
        'engine_power',
        'power_kw',
        'power_hp',
        'rego_state',
        'rego_expiry',
        'build_date',
        'compliance_date',
        'gcm',
        'gvm',
        'tare',
        'sleeping_capacity',
        'toilet',
        'shower',
        'air_conditioning',
        'fridge',
        'stereo',
        'gps',
        'standard_features',
        'optional_features',
        'adv_description',
        'short_description',
        'yard_code',
        'series',
        'nvic',
        'redbook_code',
        'stock_type',
        'is_demo',
        'is_special',
        'is_prestiged',
        'is_used',
        'is_dap',
        'is_miles',
        'is_featured',
        'stock_status',
        'warranty',
        'towball_weight',
        'images',
        'created_by',
    ];

    protected $casts = [
        'images' => 'array',
        'features'=>'array',
        'toilet' => 'boolean',
        'shower' => 'boolean',
        'air_conditioning' => 'boolean',
        'fridge' => 'boolean',
        'stereo' => 'boolean',
        'gps' => 'boolean',
        'is_demo' => 'boolean',
        'is_special' => 'boolean',
        'is_prestiged' => 'boolean',
        'is_used' => 'boolean',
        'is_dap' => 'boolean',
        'is_miles' => 'boolean',
        'is_featured' => 'boolean',
    ];
}
